download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","hpc.zip")
unzip("/Users/user/datasciencecoursera/hpc.zip")
hpc <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$date_time <- ymd_hms(paste(hpc$Date, hpc$Time))
newhpc <- subset(hpc, hpc$Date>="2007-02-01" & hpc$Date<="2007-02-02")
newhpc$Global_active_power <- as.numeric(as.character(newhpc$Global_active_power))
newhpc$Global_reactive_power <- as.numeric(as.character(newhpc$Global_reactive_power))
newhpc$Sub_metering_1 <- as.numeric(as.character(newhpc$Sub_metering_1))
newhpc$Sub_metering_2 <- as.numeric(as.character(newhpc$Sub_metering_2))
newhpc$Sub_metering_3 <- as.numeric(as.character(newhpc$Sub_metering_3))
newhpc$Voltage <- as.numeric(as.character(newhpc$Voltage))
png("plot3.png", width = 480, height = 480)
plot(newhpc$date_time,newhpc$Sub_metering_1, type="l", xlab = "", ylab = "Energy sub metering")
lines(newhpc$date_time,newhpc$Sub_metering_3,col="blue")
lines(newhpc$date_time,newhpc$Sub_metering_2,col="red")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1, col = c("black","red","blue") )
dev.off()