download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","hpc.zip")
unzip("/Users/user/datasciencecoursera/hpc.zip")
hpc <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$date_time <- ymd_hms(paste(hpc$Date, hpc$Time))
newhpc <- subset(hpc, hpc$Date>="2007-02-01" & hpc$Date<="2007-02-02")
newhpc$Global_active_power <- as.numeric(as.character(newhpc$Global_active_power))
png("plot2.png", width = 480, height = 480)
plot(newhpc$date_time,newhpc$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()